sonar.organization=lukasqw
sonar.projectKey=lukasqw_oficina-tech-ms2-os-service
sonar.projectName=Oficina Tech MS2 OS Service
sonar.projectVersion=1.0
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/docs/**,**/*.pb.go,**/.github/**,**/Dockerfile,**/.dockerignore,**/docker-compose*.yml,**/*mock*.go,**/k8s/**,**/*.sh,**/bin/**,**/.env,**/.git/**,.gocache/**,**/bdd/**,**/features/**,**/cmd/**,**/internal/modules/service_order/module.go,**/internal/modules/service_order/infra/http/routes.go,**/internal/modules/service_order/infra/http/dto/**,**/internal/modules/service_order/infra/persistence/**,**/internal/modules/service_order/infra/adapters/implementations/**,**/internal/shared/dto/**,**/internal/shared/infra/awsconfig/**,**/internal/shared/infra/database/**,**/internal/shared/infra/dynamodb/**,**/internal/shared/infra/email/**,**/internal/shared/infra/sqs/**,**/internal/messaging/events/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
